[project]
name = "andy-glm"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Andy Weaver", email = "andrewayersweaver+github@gmail.com" }
]
dependencies = [
    "duckdb>=0.9",
]
readme = "README.md"
requires-python = ">= 3.8"
license = { text = "MIT" }
